apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-service-cert
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}